[project]
name = "ham-maze-stacks"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = ".\.cache"

[contracts.ham-maze-v2]
path = "contracts/ham-maze-v2.clar"
depends_on = []

[contracts.ham-maze-v3]
path = "contracts/ham-maze-v3.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]
